const COUNTRY_CODES: Record<string, string> = {
  Sweden: "SE",
  Denmark: "DK",
  Germany: "DE",
  Netherlands: "NL",
  Belgium: "BE",
  France: "FR",
  Spain: "ES",
  Portugal: "PT",
  Italy: "IT",
  Greece: "GR",
  Turkey: "TR",
  Croatia: "HR",
  Montenegro: "ME",
  Albania: "AL",
  Slovenia: "SI",
  "United Kingdom": "GB",
  Norway: "NO",
  Finland: "FI",
  Poland: "PL",
  Ireland: "IE",
  Malta: "MT",
  Cyprus: "CY",
  Monaco: "MC",
  Tunisia: "TN",
  Morocco: "MA",
  Algeria: "DZ",
  Gibraltar: "GI",
  "Bosnia and Herzegovina": "BA",
  Estonia: "EE",
  Latvia: "LV",
  Lithuania: "LT",
  Romania: "RO",
  Bulgaria: "BG",
  Egypt: "EG",
  Libya: "LY",
  Israel: "IL",
  Lebanon: "LB",
  Syria: "SY",
  Iceland: "IS",
  "Faroe Islands": "FO",
  Greenland: "GL",
  Russia: "RU",
  Ukraine: "UA",
  Georgia: "GE",
  Senegal: "SN",
  "Cabo Verde": "CV",
  "Cape Verde": "CV",
  Gambia: "GM",
  Mauritania: "MR",
};

export function countryToFlag(countryName: string | null): string {
  if (!countryName) return "";
  const code = COUNTRY_CODES[countryName];
  if (!code) return "";
  return String.fromCodePoint(
    ...code.split("").map((c) => 0x1f1e6 + c.charCodeAt(0) - 65),
  );
}
