export type LegalDocumentKey = "privacy" | "terms";

export interface LegalSection {
  title: string;
  paragraphs: string[];
  bullets?: string[];
}

export interface LegalDocumentContent {
  key: LegalDocumentKey;
  path: `/legal/${LegalDocumentKey}`;
  title: string;
  description: string;
  effectiveDate: string;
  publicationStatusNote?: string;
  intro: string[];
  sections: LegalSection[];
}

export const legalDocuments: Record<LegalDocumentKey, LegalDocumentContent> = {
  privacy: {
    key: "privacy",
    path: "/legal/privacy",
    title: "Privacy Policy",
    description:
      "How Bosco collects, uses, stores, shares, and deletes personal data for sailing voyages, accounts, and public sharing.",
    effectiveDate: "March 30, 2026",
    intro: [
      "Bosco is a sailing logbook and voyage-sharing service. This Privacy Policy explains what personal data Bosco handles, why it is handled, which service providers are involved, and what rights you have over that data.",
      "Bosco publishes this Privacy Policy under the Bosco product name for the live service and its official app-store listings.",
      "Privacy requests and GDPR questions can be submitted through Bosco's published support and contact channels for the live service.",
    ],
    sections: [
      {
        title: "Data Bosco collects",
        paragraphs: [
          "Bosco processes the information required to create an account, build voyages, and share them on the web or in the app.",
        ],
        bullets: [
          "Account and identity data such as your auth email, profile username, boat name, boat type, biography, and profile photos.",
          "Voyage content such as GPX tracks, historical coordinates, route geometry, stopovers, voyage titles and descriptions, journal entries, uploaded photos, and any cover imagery you choose to attach to a voyage.",
          "Authentication and session data needed to keep you signed in and secure your account.",
          "Technical observability and analytics signals such as page usage, performance metrics, browser/runtime diagnostics, and error events generated by Vercel Analytics, Speed Insights, and Sentry.",
        ],
      },
      {
        title: "Why Bosco uses personal data",
        paragraphs: [
          "Bosco uses personal data to operate the service, authenticate accounts, render your voyages, support public sharing when you enable it, diagnose failures, and keep the product reliable and secure.",
        ],
        bullets: [
          "Provide magic-link authentication and account access.",
          "Store and render your sailor profile, voyage history, maps, stopovers, journal entries, and uploaded photos.",
          "Reverse geocode stopover coordinates into place names.",
          "Measure availability, performance, and product reliability, and investigate errors or abuse.",
        ],
      },
      {
        title: "Public voyages and consent",
        paragraphs: [
          "GPS tracks and location history are personal data. Bosco treats private voyages as owner-only content. When you choose to make a voyage public, you explicitly decide to expose its route, stopovers, and any attached public content on the web.",
          "You remain responsible for deciding whether a voyage, route segment, stopover, journal entry, or photo should be shared publicly.",
        ],
      },
      {
        title: "Processors and external services",
        paragraphs: [
          "Bosco uses the following service providers to deliver the product and operate the platform.",
        ],
        bullets: [
          "Supabase for authentication, database storage, and file storage.",
          "Vercel for hosting, delivery, web analytics, and performance insights.",
          "Sentry for error monitoring, diagnostics, and sampled session replay or troubleshooting data.",
          "Nominatim for reverse geocoding coordinates into human-readable place names.",
        ],
      },
      {
        title: "Retention and deletion",
        paragraphs: [
          "Bosco keeps account and voyage data for as long as your account remains active or until deletion is requested. Public content remains visible until you make it private, remove it, or delete the associated account data.",
          "When you request account deletion, Bosco aims to remove the related voyages, legs, stopovers, log entries, photos, and associated account data within 30 days, subject to short-lived backups, security logs, or legal obligations that require limited retention.",
        ],
      },
      {
        title: "Your rights",
        paragraphs: [
          "Depending on your location, including under GDPR, you may have rights to access, correct, export, restrict, object to certain processing, or delete your personal data.",
          "If Bosco relies on your choice to make voyage data public, you can withdraw that choice by switching the voyage back to private or asking Bosco to delete the content.",
        ],
      },
      {
        title: "Security summary",
        paragraphs: [
          "Bosco uses managed infrastructure, authenticated access controls, HTTPS transport, and operational monitoring to reduce the risk of unauthorized access or service disruption.",
          "No internet service can guarantee perfect security. You should avoid uploading personal data you are not comfortable storing online or exposing through public voyage sharing.",
        ],
      },
    ],
  },
  terms: {
    key: "terms",
    path: "/legal/terms",
    title: "Terms of Service",
    description:
      "The rules for using Bosco, including account responsibilities, user content, public sharing, third-party dependencies, and service availability.",
    effectiveDate: "March 30, 2026",
    intro: [
      "These Terms of Service govern your use of Bosco, a sailing voyage logbook and sharing service.",
      "By creating an account or using Bosco, you agree to follow these Terms and any product policies referenced by them.",
      "Bosco publishes these Terms under the Bosco product name for the live service and its official app-store listings.",
    ],
    sections: [
      {
        title: "Service scope",
        paragraphs: [
          "Bosco lets you create an account, import or manage voyage data, publish selected voyages publicly, and share the resulting web pages with other people.",
        ],
      },
      {
        title: "Accounts and security",
        paragraphs: [
          "You are responsible for the accuracy of the account information you provide and for maintaining control of the email account used to access Bosco.",
          "You must not use Bosco to gain unauthorized access, interfere with another user's content, or attempt to bypass security or access controls.",
        ],
      },
      {
        title: "Your content and Bosco's license",
        paragraphs: [
          "You keep ownership of the content you upload or create in Bosco, including GPX tracks, route coordinates, stopovers, journal entries, photos, and profile details.",
          "You grant Bosco the limited license needed to host, process, back up, display, and transmit that content so the service can function.",
        ],
      },
      {
        title: "Public sharing responsibility",
        paragraphs: [
          "When you make a voyage public, you instruct Bosco to display that route and any attached public content to anyone who has the link or finds the page.",
          "You are responsible for making sure you have the right to upload and publicly share the locations, text, and images you publish through Bosco.",
        ],
      },
      {
        title: "Acceptable use",
        paragraphs: [
          "You must not use Bosco to upload unlawful material, infringing content, malware, deceptive content, or data that violates another person's privacy, confidentiality, or intellectual-property rights.",
          "Bosco may suspend or remove content or accounts that create security, legal, or operational risk for the service or its users.",
        ],
      },
      {
        title: "Third-party services",
        paragraphs: [
          "Bosco depends on third-party infrastructure and data providers, including authentication, hosting, observability, analytics, and reverse-geocoding services.",
          "Those services may change, fail, or impose their own limits. Bosco is not responsible for outages or policy changes originating from third-party providers.",
        ],
      },
      {
        title: "Availability and disclaimers",
        paragraphs: [
          "Bosco is provided on a best-effort basis. Features, interfaces, and availability may change without notice, especially while the product is still evolving.",
          "Bosco is not a navigation, safety, or emergency-response tool. Do not rely on it for real-time routing, collision avoidance, or regulatory compliance.",
        ],
      },
      {
        title: "Termination and deletion",
        paragraphs: [
          "You can stop using Bosco at any time and ask Bosco to delete your account. Account deletion and data erasure requests are handled through Bosco's privacy and account-deletion process.",
          "Bosco may suspend or terminate access when necessary to investigate abuse, security issues, unlawful activity, or repeated Terms violations.",
        ],
      },
      {
        title: "Updates and contact",
        paragraphs: [
          "Bosco may update these Terms as the product evolves. The current version should always show its effective date, and material changes should be communicated through a reasonable publication channel.",
          "Questions about these Terms can be sent through Bosco's published support and contact channels for the live service.",
        ],
      },
    ],
  },
};
